# fly.toml app configuration file generated for red-dust-2299 on 2023-08-08T14:38:09-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "red-dust-2299"
primary_region = "den"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "red-dust-2299.fly.dev"
  PORT = "8080"
  DATABASE_PATH = "/mnt/sqlite"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
